### ISSUE TITLE
Change to broth URL

### ISSUE THREAD

**Issue by leafo** [yeslayla/butler-publish-itchio-action#12]
https://github.com/yeslayla/butler-publish-itchio-action/blob/83ce22b4f586a26e2e4cab8fe9213fd1cd9fae97/Dockerfile#L11

We're migrating domains to `broth.itch.zone` from `broth.itch.ovh` (`itch.zone` is replacing all `itch.ovh` URLs). The broth URL is now: https://broth.itch.zone/

The old URL will 301 redirect but we recommend everyone migrate to using the latest URL.

**Comment by yeslayla** [comment]
Updated https://github.com/yeslayla/butler-publish-itchio-action/commit/b5f0b072e8b12b731c69f12b5430f594700e0947 :smile:
