### ISSUE TITLE
CentOS 8 end of life

### ISSUE THREAD

**Issue by Apostolique** [yeslayla/butler-publish-itchio-action#8]
It looks like CentOS 8 went EOL in December 2021 according [this](https://www.centos.org/centos-linux-eol/). 

This broke my pipelines that use this GitHub action. I now get the following error:

> Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

**Comment by yeslayla** [comment]
Moved container to Rocky Linux, if issues persist. Let me know. Thank you!

**Comment by Apostolique** [comment]
Can confirm that my builds passed instantly.

**Comment by drhayes** [comment]
Came here to file the same bug, saw that you'd already fixed it. Thanks!
